server:
  port: 3002
  error:
    include-stacktrace: "always"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vecnamoda?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/vecnamoda?serverTimezone=UTC
    user: root
    password: 1234
    schemas: vecnamoda
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  mvc:
    log-resolved-exception: true

security:
  jwt:
    secret: 64JimYzFeqqLT8Ek